name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windowsbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure MSVC
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64
        spectre: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: 6.8.0
    - name: Configure
      run: cmake ./minigames/pong
    - name: Build
      run: cmake --build ./minigames/pong --target pong.exe --config Release -- -j4
